<p style="text-align:center">
    <a href="https://skills.network/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork899-2023-01-01">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# Peer Review Assignment - Data Engineer - ETL

Estimated time needed: **20** minutes

## Objectives

In this final part you will:

- Run the ETL process
- Extract bank and market cap data from the JSON file `bank_market_cap.json`
- Transform the market cap currency using the exchange rate data
- Load the transformed data into a seperate CSV

For this lab, we are going to be using Python and several Python libraries. Some of these libraries might be installed in your lab environment or in SN Labs. Others may need to be installed by you. The cells below will install these libraries when executed.

In [ ]:
#!mamba install pandas==1.3.3 -y
#!mamba install requests==2.26.0 -y

## Imports

Import any additional libraries you may need here.

In [1]:
import glob
import pandas as pd
from datetime import datetime

As the exchange rate fluctuates, we will download the same dataset to make marking simpler. This will be in the same format as the dataset you used in the last section

In [2]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_1.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Lab%20-%20Extract%20Transform%20Load/data/bank_market_cap_2.json
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0221EN-SkillsNetwork/labs/module%206/Final%20Assignment/exchange_rates.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.
'wget' is not recognized as an internal or external command,
operable program or batch file.

## Extract

### JSON Extract Function

This function will extract JSON files.

In [3]:
def extract_from_json(file_to_process):
    dataframe = pd.read_json(file_to_process)
    return dataframe

## Extract Function

Define the extract function that finds JSON file `bank_market_cap_1.json` and calls the function created above to extract data from them. Store the data in a `pandas` dataframe. Use the following list for the columns.

In [4]:
columns=['Name','Market Cap (US$ Billion)']

In [5]:
def extract(file, file_type):
    # Write your code here
    personal_path = 'C:\\Users\\Rattapong.Pojpatin\\Downloads\\{}'.format(file)
    if file_type == 'json':
        df = pd.read_json(personal_path)
    elif file_type == 'csv':
        df = pd.read_csv(file)
    df.columns = columns
    return df

<b>Question 1</b> Load the file <code>exchange_rates.csv</code> as a dataframe and find the exchange rate for British pounds with the symbol <code>GBP</code>, store it in the variable  <code>exchange_rate</code>, you will be asked for the number. Hint: set the parameter  <code>index_col</code> to 0.

In [6]:
# Write your code here
df_exchange_rates = extract(
    file = 'exchange_rates.csv',
    file_type = 'csv'
)
exchange_rate = float(df_exchange_rates[df_exchange_rates['Name'] == 'GBP'].iloc[:,1])
exchange_rate

0.7323984208000001

## Transform

Using <code>exchange_rate</code> and the `exchange_rates.csv` file find the exchange rate of USD to GBP. Write a transform function that

1. Changes the `Market Cap (US$ Billion)` column from USD to GBP
2. Rounds the Market Cap (US$ Billion)` column to 3 decimal places
3. Rename `Market Cap (US$ Billion)` to `Market Cap (GBP$ Billion)`

In [7]:
def transform(df, exchange_rate):
    # Write your code here
    df_new = df
    df_new['Market Cap (GBP$ Billion)'] = round(df_new['Market Cap (US$ Billion)'] / exchange_rate, 3)
    df_new.drop('Market Cap (US$ Billion)', axis = 1, inplace = True)
    return df_new

## Load

Create a function that takes a dataframe and load it to a csv named `bank_market_cap_gbp.csv`. Make sure to set `index` to `False`.

In [8]:
def load(df, file_name):
    # Write your code here
    df.to_csv(file_name, index = False)

## Logging Function

Write the logging function <code>log</code> to log your data:

In [9]:
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)
console = logging.StreamHandler()
console.setLevel(level=logging.INFO)
formatter =  logging.Formatter('%(asctime)s : %(message)s')
console.setFormatter(formatter)
logger.addHandler(console)

In [10]:
def log(message):
    # Write your code here
    logger.info(message)

## Running the ETL Process

Log the process accordingly using the following <code>"ETL Job Started"</code> and <code>"Extract phase Started"</code>

### Extract

<code>Question 2</code> Use the function <code>extract</code>, and print the first 5 rows, take a screen shot:

In [15]:
# Call the function here
df = extract(
    file = 'bank_market_cap_1.json',
    file_type = 'json'
)
# Print the rows here
df.head()

                                      Name  Market Cap (US$ Billion)
0                           JPMorgan Chase                   390.934
1  Industrial and Commercial Bank of China                   345.214
2                          Bank of America                   325.331
3                              Wells Fargo                   308.013
4                  China Construction Bank                   257.399

Log the data as <code>"Extract phase Ended"</code>

In [16]:
# Write your code here
log('Extract phase Ended')

2023-06-04 11:49:21,756 : Extract phase Ended

### Transform

Log the following  <code>"Transform phase Started"</code>

In [17]:
# Write your code here
log('Transform phase Started')

2023-06-04 11:49:34,847 : Transform phase Started

<code>Question 3</code> Use the function <code>transform</code> and print the first 5 rows of the output, take a screen shot:

In [18]:
# Call the function here
df = transform(
    df = df,
    exchange_rate = exchange_rate
)
# Print the first 5 rows here
df.head()

                                      Name  Market Cap (GBP$ Billion)
0                           JPMorgan Chase                    533.772
1  Industrial and Commercial Bank of China                    471.347
2                          Bank of America                    444.199
3                              Wells Fargo                    420.554
4                  China Construction Bank                    351.447

Log your data <code>"Transform phase Ended"</code>

In [19]:
# Write your code here
log('Transform phase Ended')

2023-06-04 11:50:28,589 : Transform phase Ended

### Load

Log the following `"Load phase Started"`.

In [20]:
# Write your code here
log('Load phase Started')

2023-06-04 11:50:39,902 : Load phase Started

Call the load function

In [21]:
# Write your code here
load(
    df = df,
    file_name = 'bank_market_cap_gbp.csv'
)

Log the following `"Load phase Ended"`.

In [22]:
# Write your code here
log('Load phase Ended')

2023-06-04 11:51:42,834 : Load phase Ended

## Authors

Ramesh Sannareddy, Joseph Santrcangelo and Azim Hirjani

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-11-25        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

 Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkPY0221ENSkillsNetwork899-2023-01-01&cm_mmc=Email_Newsletter-_-Developer_Ed%2BTech-_-WW_WW-_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).